### ISSUE TITLE
Suggestion for gitstream GitHub action

### ISSUE THREAD

**Issue by SallyBlichG** [linear-b/gitstream-github-action#41]
Hello,

We've been using the gitstream GitHub action, and it has been working well for us. I wanted to suggest a couple of enhancements that could make it even more useful for our specific needs:

1. **Conditional execution**: It would be beneficial to have the ability to pass an option or condition to the action, so it doesn't run on every event. For instance, when someone adds a comment, the action currently runs. It would be great to control this behavior using a condition like this one` if: !${{ github.event.issue.pull_request }} `to make the action execute only when a new commit occurs.

https://github.com/linear-b/gitstream-github-action/blob/2403e61966823a11081a26b960aaa676e9965f56/action.yml#L84

2. **Email notification on failure only**: Currently, the action sends an email notification each time gitstream runs. It would be really helpful if there's an option to receive an email only when the gitstream action itself fails, rather than for every run. This way, we can be promptly notified of any issues with the action specifically.

     The default behavior is to send an email only when a workflow failed, It will be great if it will be the same.
![image](https://github.com/linear-b/gitstream-github-action/assets/129067029/c1395bfe-3e1b-434d-8c59-5f8decfca4b8)
     https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#github-actions-notification-options

We believe these additions would significantly improve the flexibility and usability of the gitstream action for our team.

Thank you for considering our suggestions!

**Comment by vim-zz** [comment]
Thank you @SallyBlichG for your feedback, we are working on allowing you to control when gitStream triggers, e.g. only on commits. I expect it to be ready the coming month. You can watch for new features here: https://github.com/linear-b/gitstream/discussions/102

I will also look at your other suggestion.

For future issues, you should open issues on gitStream main GitHub repo: https://github.com/linear-b/gitstream

**Comment by vim-zz** [comment]
@SallyBlichG as for your 2nd ask, please open a new issue here: https://github.com/linear-b/gitstream

Please also include and exmaple of a notification you don't wont to get, the more examples it is easier to design a solution.
